config/routes.rb
Foodgenie::Application.routes.draw do

  # Forms
  resources :blender_forms
  resources :genie_search_forms
  match '/blender' => "blender_forms#new"

  # Data 
  resources :ingredients
  resources :categories
  resources :recipes
  resources :food_items, :collection => {:formatted => [:get, :post]}

  # Default root
  root to: 'genie_search_forms#new'  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  attr_accessible :ingredients, :many_ppl, :title, :effort_id, :time, :category_id, :text, :approved, :ingredients_attributes

  has_many :ingredients, :dependent => :destroy
  has_many :food_items, :through => :ingredients
  belongs_to :category

  accepts_nested_attributes_for :ingredients, allow_destroy: true, :reject_if => lambda { |a| a[:quantity].blank? || a[:measure].blank? }
  
  validates_uniqueness_of :title
  
  validates_presence_of :title
  validates_presence_of :effort_id
  validates_presence_of :time
  validates_presence_of :category_id  
  
  def match_recipe_with_ingredients ingredient_list, number_of_raw_ingredients
    matched_percent = 0
    unless ingredient_list.blank?
      matched_ingredients = self.food_items & ingredient_list
      matched_percent = (matched_ingredients.size*100)/number_of_raw_ingredients
      matched_percent = 100 if matched_percent > 100
    end
    return matched_percent
  end 
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(params[:recipe])

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to @recipe, notice: 'Recipe was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to recipes_url, notice: "Successfully destroyed survey."
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_food_item_fields.html.erb
<fieldset>
  <%= f.label :name, "Ingredient Name" %>
  <%= f.text_field :name %>
  <%= f.label :price, "Price" %>
  <%= f.text_field :price %>
  <%= f.label :certified, "Certified" %>
  <%= f.check_box :certified %>
</fieldset>

app/views/recipes/_form.html.erb
<%= nested_form_for @recipe do |f| %>

  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :many_ppl %><br />
    <%= f.text_field :many_ppl %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :effort_id %><br />
    <%= f.text_field :effort_id %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text, {:cols => 60, :rows => 10} %>
  </div>

  <!-- Nested Form for ingredients -->
  <%= f.fields_for :ingredients %>
  <p><%= f.link_to_add "Add Ingredient", :ingredients %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div>
	<fieldset>
		<%= f.fields_for :food_item %>
		<%= f.label :quantity, "Quantity" %><br />
		<%= f.text_field :quantity %><br />
		<%= f.label :measure, "Measure/Units" %><br />
		<%= f.text_field :measure %><br />
		<p><%= f.link_to_add "Add Item", :food_item %></p>
		<%= f.link_to_remove "Remove this ingredient" %>
	</fieldset>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Many ppl</th>
    <th>Title</th>
    <th>Difficulty</th>
    <th>Time</th>
    <th>Category</th>
    <th>Text</th>
    <th>Extra content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= recipe.many_ppl %></td>
    <td><%= recipe.title %></td>
    <td><%= recipe.effort_id %></td>
    <td><%= recipe.time %></td>
    <td><%= recipe.category_id %></td>
    <td><%= recipe.text %></td>
    <td><%= recipe.extra_content %></td>
    <td><%= link_to 'Show', recipe %></td>
    <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
    <td><%= link_to 'Destroy', recipe, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Many ppl:</b>
  <%= @recipe.many_ppl %>
</p>

<p>
  <b>Title:</b>
  <%= @recipe.title %>
</p>

<p>
  <b>Difficulty:</b>
  <%= @recipe.effort_id %>
</p>

<p>
  <b>Time:</b>
  <%= @recipe.time %>
</p>

<p>
  <b>Category:</b>
  <%= @recipe.category.name %>
</p>

<p>
  <b>Text:</b>
  <%= @recipe.text %>
</p>

<p>
  <b>Extra content:</b>
  <%= @recipe.extra_content %>
</p>

<p>
  <b>Ingredients:</b>
  <% @recipe.ingredients.each do |ingredient| %>
    <p>- <%=  ingredient.quantity %> <%=  ingredient.measure %> <%= ingredient.food_item.name %></p>
  <% end %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>