config/routes.rb
Foodgenie::Application.routes.draw do

  # Forms
  resources :blender_forms
  resources :genie_search_forms
  match '/blender' => "blender_forms#new"

  # Data 
  resources :ingredients
  resources :categories
  resources :recipes
  resources :food_items, :collection => {:formatted => [:get, :post]}

  # Default root
  root to: 'genie_search_forms#new'  

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  attr_accessible :food_item, :food_item_id, :quantity, :measure, :recipe_id, :food_item_attributes

  belongs_to :food_item
  belongs_to :recipe
  
  before_validation :find_existing_food_item
  after_destroy :destroy_associated_food_items

  accepts_nested_attributes_for :food_item, allow_destroy: true, :reject_if => lambda { |a| a[:name].blank? }

  def find_existing_food_item
    # If the inserted FoodItem already exists, gets that one.
    # The creation of the fooditem is up to the FoodItem Model itself
    unless self.food_item.nil? || self.food_item.valid?
      f_item = FoodItem.find_by_name self.food_item.name 
      self.food_item = f_item unless f_item.blank?
    end     
  end
  
  def destroy_associated_food_items
    food_items = Ingredient.find(:all, :conditions => ['food_item_id = ? and id != ?',self.food_item_id,self.id])
    self.food_item.destroy if food_items.blank?
  end 
  
  def food_item_name
    food_item.try(:name)
  end

  def pretty_print
    return "#{quantity} #{measure} #{food_item.name}"
  end
  
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def create
    @ingredient = Ingredient.new(params[:ingredient])

    if @ingredient.save
      redirect_to @ingredient, notice: 'Ingredient was successfully created.' 
    else
      render :new
    end
  end

  def update
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.update_attributes(params[:ingredient])
      redirect_to @ingredient, notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    redirect_to ingredients_url, notice: "Successfully destroyed ingredient."
  end
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :food_item_id %><br />
    <%= f.collection_select :food_item_id, FoodItem.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>Food item</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%= ingredient.food_item_id %></td>
    <td><%= ingredient.quantity %></td>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food measure', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Food item:</b>
  <%= @ingredient.food_item.name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @ingredient.quantity %>
</p>


<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>