config/routes.rb
Foodgenie::Application.routes.draw do

  # Forms
  resources :blender_forms
  resources :genie_search_forms
  match '/blender' => "blender_forms#new"

  # Data 
  resources :ingredients
  resources :categories
  resources :recipes
  resources :food_items, :collection => {:formatted => [:get, :post]}

  # Default root
  root to: 'genie_search_forms#new'  

end

app/models/food_item.rb
class FoodItem < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_presence_of :name

  has_many :ingredients  
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController

  def index
    @food_items = FoodItem.order(:name).where("name like ?", "%#{params[:term]}%")
    render json: @food_items.map(&:name)
  end

  def show
    @food_item = FoodItem.find(params[:id])
  end

  def new
    @food_item = FoodItem.new
  end

  def edit
    @food_item = FoodItem.find(params[:id])
  end

  def create
    @food_item = FoodItem.new(params[:food_item])

    if @food_item.save
      redirect_to @food_item, notice: 'Food item was successfully created.'
    else
      render :new
    end
  end

  def update
    @food_item = FoodItem.find(params[:id])

    if @food_item.update_attributes(params[:food_item])
      redirect_to @food_item, notice: 'Food item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @food_item = FoodItem.find(params[:id])
    @food_item.destroy

    redirect_to food_items_url, notice: "Successfully destroyed food item."
  end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/views/food_items/_form.html.erb
<%= form_for(@food_item) do |f| %>
  <% if @food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% @food_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing food_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<h1>Listing food_items</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @food_items.each do |food_item| %>
  <tr>
    <td><%= food_item.name %></td>
    <td><%= link_to 'Show', food_item %></td>
    <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
    <td><%= link_to 'Destroy', food_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Food item', new_food_item_path %>

app/views/food_items/index.js.erb
<%= auto_complete_result @food_items, :name %>

app/views/food_items/new.html.erb
<h1>New food_item</h1>

<%= render 'form' %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @food_item.name %>
</p>


<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>